version: '2'

services:
  web:
    image: node:10.15.3
    command: npm run dev
    working_dir: /app
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080

volumes:
  node_modules:
